<a href="https://colab.research.google.com/github/tabassum-laz/Artificial-Intelligence-Lab/blob/main/AI_Lab10_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data=[[1,2],[3,4]]
x_data= torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
arr=np.array(data)
arr

array([[1, 2],
       [3, 4]])

In [4]:
x=torch.from_numpy(arr)
x

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones= torch.ones_like(x)
x_ones

tensor([[1, 1],
        [1, 1]])

In [6]:
x_zeros= torch.zeros_like(x)
x_zeros

tensor([[0, 0],
        [0, 0]])

In [7]:
x_rand= torch.rand_like(x, dtype=torch.float)
x_rand

tensor([[0.4920, 0.7418],
        [0.8111, 0.4421]])

In [8]:
rand_tensor= torch.rand(2,3)
rand_tensor

tensor([[0.9796, 0.9866, 0.9205],
        [0.0883, 0.5883, 0.5834]])

In [9]:
ones_tensor= torch.ones(2,3, dtype=torch.float32)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
zeros_tensor= torch.zeros(2,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
rand_tensor.shape

torch.Size([2, 3])

In [12]:
rand_tensor.dtype

torch.float32

In [13]:
rand_tensor.device

device(type='cpu')

In [14]:
if torch.cuda.is_available():
    rand_tensor = rand_tensor.to('cuda')

In [15]:
 rand_tensor

tensor([[0.9796, 0.9866, 0.9205],
        [0.0883, 0.5883, 0.5834]])

In [16]:
rand_tensor[:,1]=1
rand_tensor

tensor([[0.9796, 1.0000, 0.9205],
        [0.0883, 1.0000, 0.5834]])

In [17]:
rand_tensor[0]

tensor([0.9796, 1.0000, 0.9205])

In [18]:
rand_tensor[:,0]

tensor([0.9796, 0.0883])

In [19]:
rand_tensor[...,-1]

tensor([0.9205, 0.5834])

In [20]:
rand_tensor.sum()

tensor(4.5717)

In [21]:
rand_tensor.sum().item()

4.571743965148926

In [22]:
t1= torch.cat([rand_tensor, zeros_tensor],dim=1)
t1

tensor([[0.9796, 1.0000, 0.9205, 0.0000, 0.0000, 0.0000],
        [0.0883, 1.0000, 0.5834, 0.0000, 0.0000, 0.0000]])

In [23]:
t2= torch.cat([rand_tensor, zeros_tensor],dim=0)
t2

tensor([[0.9796, 1.0000, 0.9205],
        [0.0883, 1.0000, 0.5834],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [24]:
rand_tensor.mul(ones_tensor)

tensor([[0.9796, 1.0000, 0.9205],
        [0.0883, 1.0000, 0.5834]])

In [25]:
rand_tensor.matmul(rand_tensor.T)

tensor([[2.8069, 1.6235],
        [1.6235, 1.3482]])

In [26]:
rand_tensor.add_(5)

tensor([[5.9796, 6.0000, 5.9205],
        [5.0883, 6.0000, 5.5834]])

In [27]:
n= np.ones(5)
n

array([1., 1., 1., 1., 1.])

In [28]:
t=torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [29]:
t.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [30]:
x = torch.empty(1)
print(x)

tensor([9.2646e+28])


In [31]:
x.size()

torch.Size([1])

In [32]:
x = torch.empty(2,3)
print(x)

tensor([[3.1044e-25, 3.1350e-41, 3.1133e-25],
        [3.1350e-41, 8.9683e-44, 0.0000e+00]])


In [33]:
torch.empty(2,2,3)

tensor([[[3.1109e-25, 3.1350e-41, 3.1048e-25],
         [3.1350e-41, 3.0881e+29, 1.5766e-19]],

        [[7.3313e+22, 7.2151e+22, 2.8404e+29],
         [2.3089e-12, 1.9421e+31, 2.7491e+20]]])

In [34]:
y=x.view(6)
y

tensor([3.1044e-25, 3.1350e-41, 3.1133e-25, 3.1350e-41, 8.9683e-44, 0.0000e+00])

In [35]:
z=x.view(1,-1)
z

tensor([[3.1044e-25, 3.1350e-41, 3.1133e-25, 3.1350e-41, 8.9683e-44, 0.0000e+00]])

In [36]:
a= torch.ones(2,2)
b= torch.ones(2,2)
a,b

(tensor([[1., 1.],
         [1., 1.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [37]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [38]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [39]:
a*b

tensor([[1., 1.],
        [1., 1.]])

In [40]:
a/b

tensor([[1., 1.],
        [1., 1.]])

In [41]:
a[1,1].item()

1.0

In [42]:
torch.full((2,3),50)

tensor([[50, 50, 50],
        [50, 50, 50]])