<a href="https://colab.research.google.com/github/tabassum-laz/Artificial-Intelligence-Lab/blob/main/AI_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Joining NumPy Arrays
import numpy as np

a1 = np.array([1, 2, 3])

a2 = np.array([4, 5, 6])

a = np.concatenate((a1, a2))

print(a)

[1 2 3 4 5 6]


In [ ]:
#Joining Arrays Using Stack Functions
a = np.array([1, 2, 3])

a1 = np.array([4, 5, 6])

arr = np.stack((a, a1), axis=1)

print(arr)


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#Splitting NumPy Arrays
a = np.array([1,2,3,4,5,6])
a1 = np.array_split(a,5)
print(a1)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
a1 = np.array_split(a,4)
print(a1)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [ ]:
a2=np.array_split(a, 4, axis=1)
print(a2)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64), array([], shape=(6, 0), dtype=int64)]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
a1 = np.vsplit(a, 3)
print(a1)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
a = np.array([1,2,3,4,5,4,4])
n = np.where(a == 4)
print(n)

(array([3, 5, 6]),)


In [ ]:
m = np.where(a%2 == 0)
print(m)

(array([1, 3, 5, 6]),)


In [ ]:
x = np.searchsorted(a, 4, side='right')
print(x)

7


In [ ]:
a =  np.array([1,3,5,7])
x = np.searchsorted(a,[2,4,6])
print(x)

[1 2 3]


In [ ]:
a = np.array(['laz', 'ipshi', 'tabassum'])
print(np.sort(a))

['ipshi' 'laz' 'tabassum']


In [ ]:
a = np.array([[1,2,3],[6,7,8]])
print(np.sort(a))

[[1 2 3]
 [6 7 8]]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a1 = a.reshape(2,3,2)
print(a1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
a1 = a.reshape(2, 4, 1)
print(a1)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
for x in a:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
#Iterating 3-D Arrays
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in a:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
#Iterating on Each Scalar Element
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(a):
  print(x)

1
2
3
4
5
6
7
8
